products = [
    {
        "id": "1",
        "name": "Bulalo",
        "image": "/images/bulalo.jpg",
        "category": "viand",
        "price": 45.5,
        "countInServings": 50,
        "rating": 5.0,
        "numReviews": 35,
    },
    {
        "id": "2",
        "name": "Paklay",
        "image": "/images/paklay.jpg",
        "category": "viand",
        "price": 35.0,
        "countInServings": 0,
        "rating": 5.0,
        "numReviews": 12,
    },
    {
        "id": "3",
        "name": "Fried Chicken",
        "image": "/images/fried_chicken.jpg",
        "category": "viand",
        "price": 40.0,
        "countInServings": 50,
        "rating": 4.8,
        "numReviews": 20,
    },
    {
        "id": "4",
        "name": "Bilo Bilo",
        "image": "/images/bilo_bilo.jpg",
        "category": "snack",
        "price": 20.0,
        "countInServings": 50,
        "rating": 4.3,
        "numReviews": 5,
    },
]
