# Generated by Django 4.1.7 on 2023-03-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_food_image_alter_food_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
