# Generated by Django 4.1.7 on 2023-05-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_food_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='building',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='office',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
