# Generated by Django 4.1.7 on 2023-06-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delivery_building_delivery_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='/placeholder.png', upload_to=''),
        ),
    ]
